general {
    hide_cursor = true
    immediate_render = true
}

background {
    monitor =
    color = rgb(1e1e2e)
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2

    outer_color = rgb(89b4fa)
    inner_color = rgb(313244)
    font_color = rgb(cdd6f4)

    placeholder_text = Enter Password
    fail_text = Authentication Failed

    position = 0, -20
    halign = center
    valign = center
}
