# =====================================
# Startup Services
# =====================================

# Status bar
exec-once = waybar

# Notifications
exec-once = mako

# Wallpaper
exec-once = hyprpaper

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Polkit authentication agent
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
