# =====================================
# Hyprland VMware Test Configuration
# =====================================

# VM monitor
monitor = ,preferred,auto,1


# Environment
env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_RENDERER_ALLOW_SOFTWARE,1


# Input
input {
    kb_layout = us
    follow_mouse = 1
}


# General
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    layout = dwindle
}


# Decoration
decoration {
    rounding = 8

    blur {
        enabled = true
        size = 6
        passes = 2
    }
}


# Animations
animations {
    enabled = false
}


# Terminal
$terminal = foot


# Keybindings

# Launch terminal
bind = SUPER, RETURN, exec, $terminal

# Kill active window
bind = SUPER, Q, killactive

# Exit Hyprland
bind = SUPER, M, exit

# Reload configuration
bind = SUPER, R, exec, hyprctl reload

# Screenshot selected region
bind = SUPER SHIFT, S, exec, grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png

# Screenshot entire screen
bind = SUPER, PRINT, exec, grim ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png


# Modular configuration
source = ~/.config/hypr/autostart.conf
