# ==============================
# Hyprland Base Configuration
# Arch Workstation
# ==============================

# Monitor
monitor=,preferred,auto,1


# Input
input {
    kb_layout = us
    follow_mouse = 1
}


# General
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
}


# Decorations
decoration {
    rounding = 10
}


# Terminal
$terminal = kitty


# Startup
exec-once = waybar


# Keybinds
bind = SUPER, RETURN, exec, $terminal
bind = CTRL, RETURN, exec, $terminal

bind = SUPER, Q, killactive
bind = SUPER, M, exit
