# =====================================
# Keybindings
# =====================================

# Launch terminal
bind = SUPER, RETURN, exec, $terminal

# Launch application launcher
bind = SUPER, SPACE, exec, rofi -show drun

# Kill active window
bind = SUPER, Q, killactive

# Exit Hyprland
bind = SUPER, M, exit

# Reload configuration
bind = SUPER, R, exec, hyprctl reload

# Screenshot selected region
bind = SUPER SHIFT, S, exec, grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png

# Screenshot entire screen
bind = SUPER, PRINT, exec, grim ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png
